### PR TITLE
Unscented Kalman Filter: using "state estimate" instead of "mean estimate" in the covariance equation at the predict step

### PR DESCRIPTION
**Pull request by Gluttton**
This is really minor issue.

`State` and `mean` in this context are synonyms, so technically is nothing wrong with using mean, but in my opinion using the same terms as at previous para will be better.

### CODE REVIEW

**Comment by rlabbe** [comment]
Good catch. Thanks!

**Comment by Gluttton** [comment]
Oops! It looks like I've broken layout.

**Comment by rlabbe** [comment]
Opps. Just a missing \\ at the end of a line. Please don't push a fix, I'm in the middle of another edit and I've already fixed it.

**Comment by Gluttton** [comment]
OK! Thanks!

**Pull request merged**
