### PR TITLE
Fix typos in chapter 08

### PR DESCRIPTION
**Pull request by lubkoll**

### CODE REVIEW

**Comment by rlabbe** [comment]
Thanks!

**Comment by Gluttton** [comment]
Looks like something went wrong. I'm not sure that this is consequences of the commit but [chapter 8 isn't allow now](http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/08-Designing-Kalman-Filters.ipynb).

**Comment by rlabbe** [comment]
Thanks. I just reverted the merge, and it works again.

**Comment by lubkoll** [comment]
Arg, sorry for that. Don't know what exactly I broke, maybe line endings.. I will take a look at it tomorrow.

**Pull request merged**
